---
- name: Set up an Access Port
  hosts: arista
  tasks:
    - name: set up an access port
      eos_switchport: 
        name: "{{ item.name }}"
        mode: "{{ item.mode}}"
        trunk_allowed_vlans: "{{ item.trunk_allowed_vlans }}"
        trunk_native_vlan: " {{ item.trunk_native_vlan }}"
        username: "{{ eapi_username }}"
        password: "{{ eapi_password }}"
        host: "{{ eapi_hostname }}" 
        port: "{{ eapi_port }}"
        transport: https
      with_items:
        - name: Ethernet4
          mode: trunk
          trunk_allowed_vlans: 963,964,965
          trunk_native_vlan: 1
...
