---
- name: Set up VLANs 
  hosts: pynet-sw4
    
  tasks:
    - name: napalm get facts 
      napalm_get_facts: 
        hostname: "{{ eapi_hostname }}"
        username: "{{ eapi_username }}"
        password: "{{ eapi_password }}"
        dev_os: eos
        filter: [facts, interfaces, bgp_neighbors]
      register: got_facts

    - debug:
        var: got_facts
...
